Traceback (most recent call last):
  File "/Users/user/anaconda3/lib/python3.11/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/Users/user/anaconda3/lib/python3.11/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/user/anaconda3/lib/python3.11/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/user/anaconda3/lib/python3.11/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/user/anaconda3/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/Users/user/anaconda3/lib/python3.11/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/Users/user/anaconda3/lib/python3.11/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/Users/user/anaconda3/lib/python3.11/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import pandas as pd                             # general data organisation         
import numpy as np                              # general work with matrices and vectors
from itables import init_notebook_mode, show    # to help visualize data frames
init_notebook_mode(all_interactive=True)        # interactive table turned on


full_dataset = pd.read_csv("data/Zhou et al 2020 Data.csv", index_col="Observation")
grasslands = full_dataset[full_dataset['Biomes'] == 'Grassland']

# drop the first 9 columns as we don't need these and they take up a lot of space 
grasslands = grasslands.drop(grasslands.columns[:9], axis=1)

show(grasslands)
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mModuleNotFoundError[0m                       Traceback (most recent call last)
Cell [0;32mIn[1], line 3[0m
[1;32m      1[0m [38;5;28;01mimport[39;00m [38;5;21;01mpandas[39;00m [38;5;28;01mas[39;00m [38;5;21;01mpd[39;00m                             [38;5;66;03m# general data organisation         [39;00m
[1;32m      2[0m [38;5;28;01mimport[39;00m [38;5;21;01mnumpy[39;00m [38;5;28;01mas[39;00m [38;5;21;01mnp[39;00m                              [38;5;66;03m# general work with matrices and vectors[39;00m
[0;32m----> 3[0m [38;5;28;01mfrom[39;00m [38;5;21;01mitables[39;00m [38;5;28;01mimport[39;00m init_notebook_mode, show    [38;5;66;03m# to help visualize data frames[39;00m
[1;32m      4[0m init_notebook_mode(all_interactive[38;5;241m=[39m[38;5;28;01mTrue[39;00m)        [38;5;66;03m# interactive table turned on[39;00m
[1;32m      7[0m full_dataset [38;5;241m=[39m pd[38;5;241m.[39mread_csv([38;5;124m"[39m[38;5;124mdata/Zhou et al 2020 Data.csv[39m[38;5;124m"[39m, index_col[38;5;241m=[39m[38;5;124m"[39m[38;5;124mObservation[39m[38;5;124m"[39m)

[0;31mModuleNotFoundError[0m: No module named 'itables'
ModuleNotFoundError: No module named 'itables'

